#! /usr/bin/python

import json 
import os
import sys
import subprocess
import time
import re

print('CMake Project Runner')

def loadProject():
    if(os.path.exists('.cmake-project.json')):
        with open('.cmake-project.json') as json_file:
            return json.load(json_file)

    return None

def run(exe):
    exePath = "build/src/exe/%s/%s" % (exe, exe)
    if not os.path.exists(exePath):
        return None

    print("")
    start = time.time()

    p = subprocess.Popen("./" + exePath,stdin=subprocess.PIPE)
    p.communicate('command')

    end = time.time()

    s = end - start
    print("\n\033[0;32mRun finished in %fs\033[0;0m" % s)
    return True

project = loadProject()
if project == None:
    print('No project found')
    exit()

if len(project['exes']) == 0:
    print("No executables to run")
    exit()

exe = project["exes"][0]
if len(sys.argv) > 1:
    exe = sys.argv[1]

print("\033[1;34mExecutable: %s\033[0;0m" % exe)
ret = run(exe)
if ret == None:
    print("Project not builded.")
    print("Use cmake-build before.")
    exit()

if ret == False:
    print('Failed to run the executable')