#! /usr/bin/python

import json 
import os
import sys
import subprocess
import time
import re
import shutil

print('CMake Project Cleaner')

def loadProject():
    if(os.path.exists('.cmake-project.json')):
        with open('.cmake-project.json') as json_file:
            return json.load(json_file)

    return None

def clear(names):

    for name in names:

        if name == "all":
            shutil.rmtree("build")
            return True

        path = "build/src/exe/%s" % name
        if not os.path.exists(path):
            path = "build/src/lib/%s" % name
            if not os.path.exists(path):
                continue

        shutil.rmtree(path)
    
    return True

project = loadProject()
if project == None:
    print('No project found')
    exit()

names = ["all"]
if len(sys.argv) > 1:
    names = sys.argv[1:]

print("\033[1;34mCleaning: %s\033[0;0m" % names)
ret = clear(names)

if ret == False:
    print('Failed to clean the project')